version: "3.7"
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:15.0
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./volume/:/docker-entrypoint-initdb.d/
    shm_size: 1g
    environment:
      POSTGRES_DB: "users-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command: ["postgres", "-c", "log_statement=all", "-c", "log_lock_waits=on"]

  client-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       DOCKER_BUILDKIT: 1
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  pg-data:


